version: '3'

networks:
  cinetwork:
    driver: bridge

volumes:
  jenkins-data:
  war-data:
  nexus-data:

services:
  sonarqube:
    image: library/sonarqube:lts
    networks:
      - cinetwork
    ports:
      - 9000:9000
    container_name: ci-sonarqube
  nexus:
    image: sonatype/nexus
    volumes:
      - nexus-data:/sonatype-work
    ports:
      - 8081:8081
    networks:
      - cinetwork
    container_name: ci-nexus
  jenkins:
    image: jenkins/jenkins:lts
    networks:
      - cinetwork
    ports:
      - 8082:8080
    privileged: true
    user: root
    volumes:
      - jenkins-data:/var/jenkins_home
      - war-data:/var/war
    container_name: ci-jenkins
  tomcat:
    image: tomcat:8.5-alpine
    networks:
      - cinetwork
    ports:
      - 8080:8080
    volumes:
      - war-data:/usr/local/tomcat/webapps
    container_name: ci-tomcat

